network: bridge
node:
  - name: master
    inerface: ens33
    ip: 192.168.245.168
    cidr: 172.18.10.0/24
    gateway: 172.18.10.1
    vxlan:
      ip: 172.18.10.0/32
      mac: f6:35:84:38:60:f1
    containers:
      - name: container1
        ip: 172.18.10.2
        veth0: veth0container1
        veth1: veth1container1
        containerPort: 3000
        hostPort: 3000
  - name: node1
    inerface: ens33
    ip: 192.168.245.172
    cidr: 172.18.20.0/24
    gateway: 172.18.20.1
    vxlan:
      ip: 172.18.20.0/32
      mac: 16:8f:3f:90:b9:2e
    containers:
      - name: container2
        ip: 172.18.20.2
        veth0: veth0container2
        veth1: veth1container2
        containerPort: 3000
        hostPort: 3000
